# yaml-language-server: $schema=https://json.schemastore.org/traefik-v2-file-provider.json
http:
  routers:
    traefik-router:
      rule: 'Host(`proxy.{{ env "PUBLIC_HOSTNAME" }}`)'
      service: traefik-service
      middlewares:
        - authelia
      entryPoints:
        - websecure
      tls:
        certResolver: cloudflare
  services:
    traefik-service:
      loadBalancer:
        servers:
          - url: 'http://{{ env "HOST_IP" }}:8090'
